08_AJAX_with_django/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('profile/<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

08_AJAX_with_django/crud/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('<int:user_pk>/password/', views.change_password, name='change_password'),
]

08_AJAX_with_django/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    followings = models.ManyToManyField(
        'self', symmetrical=False, related_name='followers'
    )

08_AJAX_with_django/articles/models.py
# articles/models.py
from django.db import models
from django.conf import settings


class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='like_articles'
    )
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

08_AJAX_with_django/accounts/forms.py
# accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email',)

08_AJAX_with_django/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
# django 와 http 에 맞춰서 JSON 형태의 데이터를 Response 할 수 있도록 해줌.
from django.http import JsonResponse

from .forms import CustomUserCreationForm, CustomUserChangeForm


def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        # form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('articles:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


from django.contrib.auth import logout as auth_logout


@login_required
def logout(request):
    auth_logout(request)
    return redirect('articles:index')


def signup(request):
    if request.user.is_authenticated:
        return redirect('articles:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@login_required
def delete(request):
    request.user.delete()
    return redirect('articles:index')


@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        # form = CustomUserChangeForm(data=request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


from django.contrib.auth.forms import PasswordChangeForm


@login_required
def change_password(request, user_pk):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        # form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('articles:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)


from django.contrib.auth import get_user_model


def profile(request, username):
    User = get_user_model()
    person = User.objects.get(username=username)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)


@login_required
def follow(request, user_pk):
    User = get_user_model()
    person = User.objects.get(pk=user_pk)
    if person != request.user:
        if person.followers.filter(pk=request.user.pk).exists():
            person.followers.remove(request.user)
            is_follow = False
        else:
            person.followers.add(request.user)
            is_follow = True
    # return redirect('accounts:profile', person.username)
    context = {
        # 현재 팔로우 여부
        'is_follow': is_follow,
        # person 의 팔로워 수
        'follower_count': person.followers.count(), 
    }
    # context 정보를 JSON 으로 바꿈 -> django 가 지원함.
    return JsonResponse(context)

08_AJAX_with_django/accounts/templates/accounts/change_password.html
<h1>비밀번호 변경</h1>
<form action="{% url 'change_password' user.pk %}" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>

08_AJAX_with_django/accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>로그인</h1>
  <form action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
</body>
</html>

08_AJAX_with_django/accounts/templates/accounts/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>{{ person.username }}님의 프로필</h1>
  <div> 
    <div>
      팔로잉 : <span id="followings-count">{{ person.followings.all|length }}</span> / 
      팔로워 : <span id="followers-count">{{ person.followers.all|length }}</span>
    </div>
    {% if request.user != person %}
      <div>
        <form id="follow-form">
          {% csrf_token %}
          {% if request.user in person.followers.all %}
            <input id="follow-button" type="submit" value="Unfollow">
          {% else %}
            <input id="follow-button" type="submit" value="Follow">
          {% endif %}
        </form>
      </div>
    {% endif %}
  </div> 

  <hr>
  <div>
    <h2>{{ person.username }}가 작성한 게시글</h2>
    {% for article in person.article_set.all %}
      <div>{{ article.title }}</div>
    {% endfor %}
    <hr>
    <h2>{{ person.username }}가 작성한 댓글</h2> 
    {% for comment in person.comment_set.all %} 
      <div>{{ comment.content }}</div> 
    {% endfor %}
    
    <hr>
    <h2>{{ person.username }}가 좋아요한 게시글</h2> 
    {% for article in person.like_articles.all %} 
      <div>{{ article.title }}</div> 
    {% endfor %}
  </div>

  <!-- axios CDN -->
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>

    // 조작하고자 하는 대상 form 태그가 누구인지 명확하게 id로 표기해준다.
    const followForm = document.querySelector('#follow-form')

    // csrf token 정보를 가져온다.
    // name 이 carfmiddlewaretoken 인 어떤 요소를 가져와서, 그 요소의 value 만 뽑아서 쓴다.
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value

    // 현재 프로필 주인의 팔로워 수를 보여주는 span tag
    const followerCountSpan = document.querySelector("#followers-count")

    // 현재 팔로우를 했는지 안했는지 보이는 버튼튼
    const followBtn = document.querySelector('#follow-button')

    // 이 followForm 에 submit 이벤트가 발생하면,
    followForm.addEventListener('submit', function (event) {
      // 내 서버는 follow POST 를 보낸다.
      // 원래 form 은...
          // action 에 지정된 위치로, method 에 지정된 방식으로,
          // 자신이 가진 input 의 name 과 value 를 데이터로 하여 요청을 보내는 것이 역할이었다.
      event.preventDefault()  // form 의 기존 이벤트를 먼저 막는다.
      // action 에 적혀있던 경로로, method 에 적혀있던 방식으로 요청을 axios 로 보낸다.
      axios({
        url: "{% url 'accounts:follow' person.pk %}", 
        method: 'POST', 
        headers: {'X-CSRFToken': csrftoken}
      })
      .then((response) => {  // 성공했을 때
        // follow 요청을 담당하는 URL 로 POST 요청이 가고,
        // follow 담당 view 함수가 실행되어, 적절한 if 문을 통과한 후 실제 follow 기능이 실행되고,
        // profile 로 redirect 되어 profile view 함수가 profile.html 파일을 반환.
        // 반환된 html 파일의 내용을 console.log 출력한다.
        console.log(response)
        // but 응답 데이터가 HTML 이 아니라...
        // 상대방의 팔로워 수, 그리고 나에게 보여질 follow 버튼에 어떤 값이 적힐지에 대한 결과를 JSON 으로 반환.
        const followerCount = response.data.follower_count
        followerCountSpan.textContent = followerCount

        const isFollow = response.data.is_follow
        followBtn.value = isFollow ? 'unfollow' : 'follow'
      })
      .catch((err) => {  // 실패했을 때
        console.log(err)
      })
    })
  </script>
</body>
</html>

08_AJAX_with_django/accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>회원가입</h1>
  <form action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
</body>
</html>

08_AJAX_with_django/accounts/templates/accounts/update.html
<h1>회원정보 수정</h1>
<form action="{% url 'accounts:update' %}" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>